// Package wasihost implements a standalone, general-purpose WASI
// snapshot-preview1 host for binaries compiled with wasm2go. It covers
// all 40 WASI preview1 functions plus the env.call_host_function stub
// required by zeroperl-style wasm2go modules.
//
// # Usage
//
// Construct a [State] with [New], passing a callback that returns the guest's
// linear memory slice. The callback is re-invoked on every syscall so that
// memory growth events are handled transparently:
//
//	state := wasihost.New(
//	    func() []byte { return *mod.Xmemory().Slice() },
//	    wasihost.WithStdin(stdinReader),
//	    wasihost.WithStdout(stdoutWriter),
//	    wasihost.WithHostDirectoryPreopen("/", hostDir),
//	)
//	mod := zeroperl.New(state, state)
//
// # Concurrency
//
// State is not safe for concurrent use. Each wasm2go Module instance must
// have its own State, and both must be used from a single goroutine.
//
// # Memory layout
//
// All multi-byte integers written into guest memory are little-endian, per
// the WASI snapshot-preview1 specification.
package wasihost

import (
	"encoding/binary"
	"fmt"
	"io"
	"io/fs"
	"os"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"
)

// State is a WASI snapshot-preview1 host for a single wasm2go Module
// instance. It implements all X-prefixed method interfaces generated by
// wasm2go for the wasi_snapshot_preview1 and env import modules.
//
// Construct State with [New]; do not create it directly.
// State is not safe for concurrent use.
type State struct {
	mem         func() []byte
	fds         []fdEntry
	preopens    []fdEntry
	mounts      []mountEntry
	env         []string
	args        []string
	startTime   time.Time
	stdin       io.Reader
	stdout      io.Writer
	stderr      io.Writer
	trace       bool
	assertOwner bool
	ownerMu     sync.Mutex
	ownerGID    uint64
	invalidated map[int]bool // fd_renumber invalidates source slots; cleared on Xfd_close and storeOpenedFD reuse
}

// fsFile is the internal read/stat/close interface satisfied by both
// [FSFileWrap] (for fs.FS-backed files) and [osFile] (for *os.File-backed
// files). It is the element type of fdEntry.file.

// fdEntry is one slot in the WASI file-descriptor table. Slots 0-2 are
// stdin, stdout, and stderr (fdCharDev). Slots 3 through 3+len(mounts)-1
// are preopen directory entries. Higher slots are allocated dynamically
// by path_open and freed by fd_close.
type fdEntry struct {
	file             fsFile
	path             string
	fdType           byte
	offset           int64
	mount            int
	preopen          bool
	dirFile          fs.ReadDirFile
	readdirSnapshot  []fs.DirEntry
	rightsBase       uint64
	rightsInheriting uint64
	fdFlags          uint16
}

func (e fdEntry) isUnused() bool {
	return e.file == nil && e.fdType == 0
}

// mountEntry maps a guest path prefix to a host filesystem. If writable
// is true and hostRoot is set, write operations (os.Create, os.Remove,
// os.Mkdir, os.Rename, etc.) are applied to the host filesystem rooted at
// hostRoot. root is used for read-through lookups.
type mountEntry struct {
	guestPath string
	root      fs.FS
	hostRoot  string
	writable  bool
	readonly  bool // explicitly read-only via WithReadOnlyFS
}

// Option is a functional option for configuring a [State] at construction
// time. Options are applied in the order they are passed to [New].

// Option is a functional option for configuring a [State] at construction
// time. Options are applied in the order they are passed to [New].
type Option func(*State)

// ExitError is the panic value raised by proc_exit. Embedding applications
// must recover it at the wasm eval boundary to obtain the guest exit code:
//
//	defer func() {
//	    if r := recover(); r != nil {
//	        if e, ok := r.(wasihost.ExitError); ok {
//	            // e.Code is the guest exit status
//	        }
//	    }
//	}()

// ExitError is the panic value raised by proc_exit. Embedding applications
// must recover it at the wasm eval boundary to obtain the guest exit code:
//
//	defer func() {
//	    if r := recover(); r != nil {
//	        if e, ok := r.(wasihost.ExitError); ok {
//	            // e.Code is the guest exit status
//	        }
//	    }
//	}()
type ExitError struct{ Code int32 }

// Error implements the error interface. Returns a string of the form
// "exit status N" where N is the guest exit code.

// Error implements the error interface. Returns a string of the form
// "exit status N" where N is the guest exit code.
func (e ExitError) Error() string { return fmt.Sprintf("exit status %d", e.Code) }

// New creates a WASI snapshot-preview1 host state. mem is called on every
// syscall invocation to obtain the current guest linear memory slice; it is
// safe to call after memory growth events because wasm2go re-slices on grow.
//
// The returned *State satisfies the X-prefixed method interfaces generated
// by wasm2go. Pass it as both import arguments to the generated module's
// New constructor:
//
//	state := wasihost.New(func() []byte { return *mod.Xmemory().Slice() }, opts...)
//	mod   := zeroperl.New(state, state)
//
// If mem is nil, any method that accesses guest memory will panic. A nil
// mem is only safe for tests that do not exercise memory-reading methods.

// New creates a WASI snapshot-preview1 host state. mem is called on every
// syscall invocation to obtain the current guest linear memory slice; it is
// safe to call after memory growth events because wasm2go re-slices on grow.
//
// The returned *State satisfies the X-prefixed method interfaces generated
// by wasm2go. Pass it as both import arguments to the generated module's
// New constructor:
//
//	state := wasihost.New(func() []byte { return *mod.Xmemory().Slice() }, opts...)
//	mod   := zeroperl.New(state, state)
//
// If mem is nil, any method that accesses guest memory will panic. A nil
// mem is only safe for tests that do not exercise memory-reading methods.
func New(mem func() []byte, opts ...Option) *State {
	s := &State{mem: mem, startTime: time.Now(), invalidated: make(map[int]bool)}
	for _, opt := range opts {
		opt(s)
	}
	// Initialize fd table
	s.fds = make([]fdEntry, 3+len(s.mounts), 8+len(s.mounts))
	s.fds[StdinFD] = fdEntry{fdType: fdCharDev, path: "stdin", rightsBase: rightsCharDev, rightsInheriting: 0}
	s.fds[StdoutFD] = fdEntry{fdType: fdCharDev, path: "stdout", rightsBase: rightsCharDev, rightsInheriting: 0}
	s.fds[StderrFD] = fdEntry{fdType: fdCharDev, path: "stderr", rightsBase: rightsCharDev, rightsInheriting: 0}

	for i := range s.mounts {
		rb := rightsWritableDirPreopenBase
		ri := rightsWritableDirPreopenInheriting
		if s.mounts[i].readonly {
			rb = rightsReadOnlyDirPreopen
			ri = rightsReadOnlyDirPreopen
		}
		s.fds[3+i] = fdEntry{
			path:             s.mounts[i].guestPath,
			fdType:           fdDir,
			mount:            i,
			preopen:          true,
			rightsBase:       rb,
			rightsInheriting: ri,
		}
	}
	s.preopens = s.fds[3 : 3+len(s.mounts)]

	return s
}

// WithArgs sets the argv for the WASI process, used by args_get and
// args_sizes_get. Defaults to no arguments. Multiple calls append.

// WithArgs sets the argv for the WASI process, used by args_get and
// args_sizes_get. Defaults to no arguments. Multiple calls append.
func WithArgs(args ...string) Option { return func(s *State) { s.args = append(s.args, args...) } }

// WithEnv sets the full environment variable list as "KEY=VALUE" strings,
// used by environ_get and environ_sizes_get. Callers are responsible for
// including all required entries such as PERL5LIB. Multiple calls append.

// WithEnv sets the full environment variable list as "KEY=VALUE" strings,
// used by environ_get and environ_sizes_get. Callers are responsible for
// including all required entries such as PERL5LIB. Multiple calls append.
func WithEnv(env ...string) Option { return func(s *State) { s.env = append(s.env, env...) } }

// WithReadOnlyFS adds a read-only guest filesystem mount that is explicitly
// marked as read-only in WASI preopens, reporting no write or mutation rights.

// WithReadOnlyFS adds a read-only guest filesystem mount that is explicitly
// marked as read-only in WASI preopens, reporting no write or mutation rights.
func WithReadOnlyFS(guestPath string, root fs.FS) Option {
	return func(s *State) {
		s.mounts = append(s.mounts, mountEntry{guestPath: guestPath, root: root, writable: false, readonly: true})
	}
}

// WithHostDirectoryPreopen adds a host directory as a WASI preopened directory.

// WithHostDirectoryPreopen adds a host directory as a WASI preopened directory.
func WithHostDirectoryPreopen(guestPath, hostPath string) Option {
	return func(s *State) {
		s.mounts = append(s.mounts, mountEntry{guestPath: guestPath, hostRoot: hostPath, root: os.DirFS(hostPath), writable: true})
	}
}

// WithStdin sets the io.Reader for guest fd 0. Defaults to a reader that
// returns (0, io.EOF) immediately. Defaulting to os.Stdin is deliberately
// avoided: this host is designed for embedded server use where the process
// stdin is unrelated to the guest.

// WithStdin sets the io.Reader for guest fd 0. Defaults to a reader that
// returns (0, io.EOF) immediately. Defaulting to os.Stdin is deliberately
// avoided: this host is designed for embedded server use where the process
// stdin is unrelated to the guest.
func WithStdin(r io.Reader) Option { return func(s *State) { s.stdin = r } }

// WithStdout sets the io.Writer for guest fd 1. Defaults to io.Discard.
// Defaulting to os.Stdout is deliberately avoided; accidental stdout
// leakage is a correctness hazard in embedded server use.

// WithStdout sets the io.Writer for guest fd 1. Defaults to io.Discard.
// Defaulting to os.Stdout is deliberately avoided; accidental stdout
// leakage is a correctness hazard in embedded server use.
func WithStdout(w io.Writer) Option { return func(s *State) { s.stdout = w } }

// WithStderr sets the io.Writer for guest fd 2. Defaults to io.Discard.
// See [WithStdout] for rationale.

// WithStderr sets the io.Writer for guest fd 2. Defaults to io.Discard.
// See [WithStdout] for rationale.
func WithStderr(w io.Writer) Option { return func(s *State) { s.stderr = w } }

// WithTracing enables per-syscall trace logging to os.Stdout. Off by
// default. In the embedding application, activate via the
// EXIFTOOL_WASI_TRACE=1 environment variable.

// WithTracing enables per-syscall trace logging to os.Stdout. Off by
// default. In the embedding application, activate via the
// EXIFTOOL_WASI_TRACE=1 environment variable.
func WithTracing() Option { return func(s *State) { s.trace = true } }

// WithOwnerAssertion enables a runtime goroutine-ownership assertion. When
// enabled, any WASI call from a goroutine other than the first caller
// panics with a descriptive message. Off by default. In the embedding
// application, activate via the EXIFTOOL_WASI_ASSERT_OWNER=1 environment
// variable.

// WithOwnerAssertion enables a runtime goroutine-ownership assertion. When
// enabled, any WASI call from a goroutine other than the first caller
// panics with a descriptive message. Off by default. In the embedding
// application, activate via the EXIFTOOL_WASI_ASSERT_OWNER=1 environment
// variable.
func WithOwnerAssertion() Option { return func(s *State) { s.assertOwner = true } }

// Mem returns the current guest linear memory slice by invoking the mem
// callback passed to [New]. The returned slice may be replaced after any
// memory growth event; callers must not retain it across calls.

// Mem returns the current guest linear memory slice by invoking the mem
// callback passed to [New]. The returned slice may be replaced after any
// memory growth event; callers must not retain it across calls.
func (s *State) Mem() []byte { return s.mem() }

// allocFD returns the index of the first empty fd-table slot above the
// preopen range. It extends the table by one slot if no free slot exists.

// allocFD returns the index of the first empty fd-table slot above the
// preopen range. It extends the table by one slot if no free slot exists.
func (s *State) allocFD() int32 {
	s.assertSingleOwner()
	start := 3 + len(s.preopens)
	for i := start; i < len(s.fds); i++ {
		if s.fds[i].isUnused() {
			return int32(i)
		}
	}
	idx := int32(len(s.fds))
	s.fds = append(s.fds, fdEntry{})
	return idx
}

// storeOpenedFD records an opened file in the fd table, computes stored rights
// via [pathOpenStoredRights], and writes the allocated fd number to guest
// memory at fdPtr. If fdType is fdDir and file implements [fs.ReadDirFile],
// entry.dirFile is set so directory iteration works.
func (s *State) storeOpenedFD(file fsFile, guestPath string, fdType byte, parentBase, parentInh uint64, fdRightsBase, fdRightsInheriting int64, fdFlags int32, fdPtr int32) int32 {
	rb, ri := pathOpenStoredRights(parentBase, parentInh, fdType, fdRightsBase, fdRightsInheriting)
	fd := s.allocFD()
	// Clear any prior invalidation for this slot.
	delete(s.invalidated, int(fd))
	entry := fdEntry{
		file:             file,
		path:             guestPath,
		fdType:           fdType,
		rightsBase:       rb,
		rightsInheriting: ri,
		fdFlags:          uint16(fdFlags),
	}
	if fdType == fdDir {
		if df, ok := file.(fs.ReadDirFile); ok {
			entry.dirFile = df
		}
	}
	s.fds[fd] = entry
	binary.LittleEndian.PutUint32(s.mem()[fdPtr:], uint32(fd))
	return wasiESuccess
}

// logTrace writes a formatted line to os.Stdout when tracing is enabled.

// logTrace writes a formatted line to os.Stdout when tracing is enabled.
func (s *State) logTrace(format string, args ...interface{}) {
	if s.trace {
		fmt.Printf(format+"\n", args...)
	}
}

// assertSingleOwner panics if the calling goroutine is not the goroutine
// that first called a method on this State. Has no effect when
// WithOwnerAssertion was not passed to New.

// assertSingleOwner panics if the calling goroutine is not the goroutine
// that first called a method on this State. Has no effect when
// WithOwnerAssertion was not passed to New.
func (s *State) assertSingleOwner() {
	if !s.assertOwner {
		return
	}
	gid := currentGID()
	s.ownerMu.Lock()
	defer s.ownerMu.Unlock()
	if s.ownerGID == 0 {
		s.ownerGID = gid
		return
	}
	if s.ownerGID != gid {
		panic(fmt.Sprintf("wasiState single-owner invariant violated: owner goroutine=%d current goroutine=%d", s.ownerGID, gid))
	}
}

// currentGID returns the numeric ID of the calling goroutine by parsing
// the output of runtime.Stack. There is no public Go API for goroutine IDs;
// this approach is intentionally fragile by design - it is only used for
// debugging assertions, not for correctness logic.

// currentGID returns the numeric ID of the calling goroutine by parsing
// the output of runtime.Stack. There is no public Go API for goroutine IDs;
// this approach is intentionally fragile by design - it is only used for
// debugging assertions, not for correctness logic.
func currentGID() uint64 {
	var b [64]byte
	n := runtime.Stack(b[:], false)
	line := string(b[:n])
	const prefix = "goroutine "
	if !strings.HasPrefix(line, prefix) {
		panic("unable to parse goroutine id: missing prefix")
	}
	line = line[len(prefix):]
	end := strings.IndexByte(line, ' ')
	if end < 0 {
		panic("unable to parse goroutine id: missing delimiter")
	}
	id, err := strconv.ParseUint(line[:end], 10, 64)
	if err != nil {
		panic(fmt.Sprintf("unable to parse goroutine id: %v", err))
	}
	return id
}

// wasiDirInfo is a sentinel fs.FileInfo returned by DirEntriesFile.Stat.
// It satisfies the fs.FileInfo interface with directory-type metadata and
// zero values for fields that are not meaningful for virtual directory listings.
