// Package wasihost implements a standalone, general-purpose WASI
// snapshot-preview1 host for binaries compiled with wasm2go. It covers
// all 40 WASI preview1 functions plus the env.call_host_function stub
// required by zeroperl-style wasm2go modules.
//
// # Usage
//
// Construct a [State] with [New], passing a callback that returns the guest's
// linear memory slice. The callback is re-invoked on every syscall so that
// memory growth events are handled transparently:
//
//	state := wasihost.New(
//	    func() []byte { return *mod.Xmemory().Slice() },
//	    wasihost.WithStdin(stdinReader),
//	    wasihost.WithStdout(stdoutWriter),
//	    wasihost.WithWritableMount("/", hostDir, os.DirFS(hostDir)),
//	)
//	mod := zeroperl.New(state, state)
//
// # Concurrency
//
// State is not safe for concurrent use. Each wasm2go Module instance must
// have its own State, and both must be used from a single goroutine.
//
// # Memory layout
//
// All multi-byte integers written into guest memory are little-endian, per
// the WASI snapshot-preview1 specification.
package wasihost

import (
	"crypto/rand"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"
)

// WASI snapshot-preview1 errno values. Names and numeric values follow
// the specification exactly.
const (
	wasiESuccess  int32 = 0
	wasiEAcces    int32 = 2
	wasiEBadf     int32 = 8
	wasiEExist    int32 = 20
	wasiEInval    int32 = 28
	wasiEIo       int32 = 29
	wasiEIsdir    int32 = 31
	wasiENoEnt    int32 = 44
	wasiENoSys    int32 = 52
	wasiENotDir   int32 = 54
	wasiENotEmpty int32 = 55
	wasiENotSup   int32 = 56
	wasiEPerm     int32 = 63
	wasiEROFS     int32 = 66
	wasiEXdev     int32 = 75

	// WASI file descriptor type tags, written into fdstat and filestat structs.
	fdCharDev byte = 2 // character device (stdin, stdout, stderr, /dev/null)
	fdDir     byte = 3 // directory
	fdFile    byte = 4 // regular file

	// WASI rights bitmasks used in fd_fdstat_get responses.
	rightFDRead         uint64 = 1 << 0
	rightFDWrite        uint64 = 1 << 1
	rightFDSeek         uint64 = 1 << 2
	rightFdstatGet      uint64 = 1 << 5
	rightFdstatSetFlags uint64 = 1 << 6
	rightFilestatGet    uint64 = 1 << 7
	rightPollOneoff     uint64 = 1 << 14
)

// Rights bitmask bundles for regular files and character devices.
var (
	rightsRegular = rightFDRead | rightFDWrite | rightFDSeek | rightFdstatGet | rightFdstatSetFlags | rightFilestatGet
	rightsCharDev = rightFDRead | rightFDWrite | rightFdstatGet

	// WASI path_open oflags bits. Bit positions match the WASI specification.
	oflagCreat uint32 = 1 << 0 // O_CREAT: create file if it does not exist
	oflagDir   uint32 = 1 << 1 // O_DIRECTORY: fail if not a directory
	oflagExcl  uint32 = 1 << 2 // O_EXCL: fail if file already exists
	oflagTrunc uint32 = 1 << 3 // O_TRUNC: truncate file to zero length on open
)

// State is a WASI snapshot-preview1 host for a single wasm2go Module
// instance. It implements all X-prefixed method interfaces generated by
// wasm2go for the wasi_snapshot_preview1 and env import modules.
//
// Construct State with [New]; do not create it directly.
// State is not safe for concurrent use.
type State struct {
	mem         func() []byte
	fds         []fdEntry
	preopens    []fdEntry
	mounts      []mountEntry
	env         []string
	args        []string
	startTime   time.Time
	stdin       io.Reader
	stdout      io.Writer
	stderr      io.Writer
	trace       bool
	assertOwner bool
	ownerMu     sync.Mutex
	ownerGID    uint64
}

// fsFile is the internal read/stat/close interface satisfied by both
// [FSFileWrap] (for fs.FS-backed files) and [osFile] (for *os.File-backed
// files). It is the element type of fdEntry.file.
type fsFile interface {
	Read([]byte) (int, error)
	Stat() (fs.FileInfo, error)
	Close() error
}

// osFile wraps *os.File to satisfy the fsFile interface for fd entries
// backed by real host files on a writable mount. It also exposes ReadAt,
// WriteAt, Truncate, and Sync through the embedded *os.File, which are
// used by fd_read, fd_write, fd_filestat_set_size, and fd_datasync.
type osFile struct{ *os.File }

// fdEntry is one slot in the WASI file-descriptor table. Slots 0–2 are
// stdin, stdout, and stderr (fdCharDev). Slots 3 through 3+len(mounts)-1
// are preopen directory entries. Higher slots are allocated dynamically
// by path_open and freed by fd_close.
type fdEntry struct {
	file    fsFile
	path    string
	fdType  byte
	offset  int64
	mount   int
	preopen bool
	dirFile fs.ReadDirFile
	dirOff  int64
}

// mountEntry maps a guest path prefix to a host filesystem. If writable
// is true and hostRoot is set, write operations (os.Create, os.Remove,
// os.Mkdir, os.Rename, etc.) are applied to the host filesystem rooted at
// hostRoot. root is used for read-through lookups.
type mountEntry struct {
	guestPath string
	root      fs.FS
	hostRoot  string
	writable  bool
}

// Option is a functional option for configuring a [State] at construction
// time. Options are applied in the order they are passed to [New].
type Option func(*State)

// ExitError is the panic value raised by proc_exit. Embedding applications
// must recover it at the wasm eval boundary to obtain the guest exit code:
//
//	defer func() {
//	    if r := recover(); r != nil {
//	        if e, ok := r.(wasihost.ExitError); ok {
//	            // e.Code is the guest exit status
//	        }
//	    }
//	}()
type ExitError struct{ Code int32 }

// Error implements the error interface. Returns a string of the form
// "exit status N" where N is the guest exit code.
func (e ExitError) Error() string { return fmt.Sprintf("exit status %d", e.Code) }

// New creates a WASI snapshot-preview1 host state. mem is called on every
// syscall invocation to obtain the current guest linear memory slice; it is
// safe to call after memory growth events because wasm2go re-slices on grow.
//
// The returned *State satisfies the X-prefixed method interfaces generated
// by wasm2go. Pass it as both import arguments to the generated module's
// New constructor:
//
//	state := wasihost.New(func() []byte { return *mod.Xmemory().Slice() }, opts...)
//	mod   := zeroperl.New(state, state)
//
// If mem is nil, any method that accesses guest memory will panic. A nil
// mem is only safe for tests that do not exercise memory-reading methods.
func New(mem func() []byte, opts ...Option) *State {
	s := &State{mem: mem, startTime: time.Now()}
	for _, opt := range opts {
		opt(s)
	}
	// Initialize fd table
	s.fds = make([]fdEntry, 3+len(s.mounts), 8+len(s.mounts))
	s.fds[0] = fdEntry{fdType: fdCharDev, path: "stdin"}
	s.fds[1] = fdEntry{fdType: fdCharDev, path: "stdout"}
	s.fds[2] = fdEntry{fdType: fdCharDev, path: "stderr"}
	for i, m := range s.mounts {
		s.preopens = append(s.preopens, fdEntry{path: m.guestPath, fdType: fdDir, mount: i, preopen: true})
		s.fds[3+i] = fdEntry{path: m.guestPath, fdType: fdDir, mount: i, preopen: true}
	}
	return s
}

// WithArgs sets the argv for the WASI process, used by args_get and
// args_sizes_get. Defaults to no arguments. Multiple calls append.
func WithArgs(args ...string) Option { return func(s *State) { s.args = append(s.args, args...) } }

// WithEnv sets the full environment variable list as "KEY=VALUE" strings,
// used by environ_get and environ_sizes_get. Callers are responsible for
// including all required entries such as PERL5LIB. Multiple calls append.
func WithEnv(env ...string) Option { return func(s *State) { s.env = append(s.env, env...) } }

// WithMount adds a read-only guest filesystem mount. guestPath (e.g. "/",
// "/lib") is served from root. Multiple mounts may be added; path_open and
// related functions select the longest-matching guestPath prefix for any
// given guest path.
func WithMount(guestPath string, root fs.FS) Option {
	return func(s *State) {
		s.mounts = append(s.mounts, mountEntry{guestPath: guestPath, root: root})
	}
}

// WithWritableMount adds a writable guest filesystem mount. root is an
// overlay fs.FS used for read-through lookups (e.g. an embedded FS for
// stdlib files); hostRoot is the absolute host path used for write
// operations (os.Create, os.Remove, os.Mkdir, os.Rename, etc.) and for
// the primary/fallback absolute-path resolution used by path_open on root
// mounts. If root is nil, os.DirFS(hostRoot) is used as the read overlay.
//
// Writable mounts are capability-oriented FFI host path access and are not
// a security sandbox by default; they intentionally permit parent-directory
// escape (e.g. via "..") to facilitate interaction with the host filesystem.
func WithWritableMount(guestPath, hostRoot string, root fs.FS) Option {
	return func(s *State) {
		s.mounts = append(s.mounts, mountEntry{guestPath: guestPath, hostRoot: hostRoot, root: root, writable: true})
	}
}

// WithStdin sets the io.Reader for guest fd 0. Defaults to a reader that
// returns (0, io.EOF) immediately. Defaulting to os.Stdin is deliberately
// avoided: this host is designed for embedded server use where the process
// stdin is unrelated to the guest.
func WithStdin(r io.Reader) Option { return func(s *State) { s.stdin = r } }

// WithStdout sets the io.Writer for guest fd 1. Defaults to io.Discard.
// Defaulting to os.Stdout is deliberately avoided; accidental stdout
// leakage is a correctness hazard in embedded server use.
func WithStdout(w io.Writer) Option { return func(s *State) { s.stdout = w } }

// WithStderr sets the io.Writer for guest fd 2. Defaults to io.Discard.
// See [WithStdout] for rationale.
func WithStderr(w io.Writer) Option { return func(s *State) { s.stderr = w } }

// WithTracing enables per-syscall trace logging to os.Stdout. Off by
// default. In the embedding application, activate via the
// EXIFTOOL_WASI_TRACE=1 environment variable.
func WithTracing() Option { return func(s *State) { s.trace = true } }

// WithOwnerAssertion enables a runtime goroutine-ownership assertion. When
// enabled, any WASI call from a goroutine other than the first caller
// panics with a descriptive message. Off by default. In the embedding
// application, activate via the EXIFTOOL_WASI_ASSERT_OWNER=1 environment
// variable.
func WithOwnerAssertion() Option { return func(s *State) { s.assertOwner = true } }

// Mem returns the current guest linear memory slice by invoking the mem
// callback passed to [New]. The returned slice may be replaced after any
// memory growth event; callers must not retain it across calls.
func (s *State) Mem() []byte { return s.mem() }

// allocFD returns the index of the first empty fd-table slot above the
// preopen range. It extends the table by one slot if no free slot exists.
func (s *State) allocFD() int32 {
	s.assertSingleOwner()
	start := 3 + len(s.preopens)
	for i := start; i < len(s.fds); i++ {
		if s.fds[i].file == nil && s.fds[i].fdType == 0 {
			return int32(i)
		}
	}
	idx := int32(len(s.fds))
	s.fds = append(s.fds, fdEntry{})
	return idx
}

// logTrace writes a formatted line to os.Stdout when tracing is enabled.
func (s *State) logTrace(format string, args ...interface{}) {
	if s.trace {
		fmt.Printf(format+"\n", args...)
	}
}

// assertSingleOwner panics if the calling goroutine is not the goroutine
// that first called a method on this State. Has no effect when
// WithOwnerAssertion was not passed to New.
func (s *State) assertSingleOwner() {
	if !s.assertOwner {
		return
	}
	gid := currentGID()
	s.ownerMu.Lock()
	defer s.ownerMu.Unlock()
	if s.ownerGID == 0 {
		s.ownerGID = gid
		return
	}
	if s.ownerGID != gid {
		panic(fmt.Sprintf("wasiState single-owner invariant violated: owner goroutine=%d current goroutine=%d", s.ownerGID, gid))
	}
}

// currentGID returns the numeric ID of the calling goroutine by parsing
// the output of runtime.Stack. There is no public Go API for goroutine IDs;
// this approach is intentionally fragile by design — it is only used for
// debugging assertions, not for correctness logic.
func currentGID() uint64 {
	var b [64]byte
	n := runtime.Stack(b[:], false)
	line := string(b[:n])
	const prefix = "goroutine "
	if !strings.HasPrefix(line, prefix) {
		panic("unable to parse goroutine id: missing prefix")
	}
	line = line[len(prefix):]
	end := strings.IndexByte(line, ' ')
	if end < 0 {
		panic("unable to parse goroutine id: missing delimiter")
	}
	id, err := strconv.ParseUint(line[:end], 10, 64)
	if err != nil {
		panic(fmt.Sprintf("unable to parse goroutine id: %v", err))
	}
	return id
}

// wasiDirInfo is a sentinel fs.FileInfo returned by DirEntriesFile.Stat.
// It satisfies the fs.FileInfo interface with directory-type metadata and
// zero values for fields that are not meaningful for virtual directory listings.
type wasiDirInfo struct{}

func (wasiDirInfo) Name() string       { return "." }
func (wasiDirInfo) Size() int64        { return 0 }
func (wasiDirInfo) Mode() fs.FileMode  { return fs.ModeDir | 0o555 }
func (wasiDirInfo) ModTime() time.Time { return time.Time{} }
func (wasiDirInfo) IsDir() bool        { return true }
func (wasiDirInfo) Sys() any           { return nil }

// DirEntriesFile adapts a []fs.DirEntry to the fs.ReadDirFile interface.
// It is used internally by fd_readdir to serve preopen directory listings
// from fs.ReadDirFS mounts. The Entries field is exported so that tests
// can construct values directly without going through path_open.
type DirEntriesFile struct {
	Entries []fs.DirEntry
	idx     int
}

func (d *DirEntriesFile) Read(_ []byte) (int, error) { return 0, io.EOF }
func (d *DirEntriesFile) Close() error               { return nil }
func (d *DirEntriesFile) Stat() (fs.FileInfo, error) { return wasiDirInfo{}, nil }
func (d *DirEntriesFile) ReadDir(n int) ([]fs.DirEntry, error) {
	if d.idx >= len(d.Entries) {
		return nil, io.EOF
	}
	if n <= 0 || d.idx+n > len(d.Entries) {
		n = len(d.Entries) - d.idx
	}
	out := d.Entries[d.idx : d.idx+n]
	d.idx += n
	return out, nil
}

// FSFileWrap adapts an fs.File to the fd-table file interface by adding
// an explicit Seek method. If the underlying fs.File implements io.Seeker,
// Seek delegates to it; otherwise Seek returns an error. Used for
// read-only embedded-FS file entries opened via path_open.
type FSFileWrap struct{ fs.File }

func (f *FSFileWrap) Stat() (fs.FileInfo, error) {
	return f.File.Stat()
}

func (f *FSFileWrap) Seek(offset int64, whence int) (int64, error) {
	if s, ok := f.File.(io.Seeker); ok {
		return s.Seek(offset, whence)
	}
	return 0, fmt.Errorf("seek not supported")
}

// Xenviron_sizes_get implements environ_sizes_get. Writes the count of
// configured environment strings and their total buffer size (including
// null terminators) to the respective pointers in guest memory.
func (s *State) Xenviron_sizes_get(countPtr, bufSizePtr int32) int32 {
	writeStringTableSizes(s.mem(), countPtr, bufSizePtr, s.env)
	return wasiESuccess
}
// Xenviron_get implements environ_get. Writes a pointer array at envPtr
// and the corresponding null-terminated "KEY=VALUE" strings packed at
// envBufPtr into guest memory.
func (s *State) Xenviron_get(envPtr, envBufPtr int32) int32 {
	writeStringTable(s.mem(), envPtr, envBufPtr, s.env)
	return wasiESuccess
}
// Xfd_prestat_get implements fd_prestat_get. Returns the prestat struct
// for the preopen directory at fd. Returns EBADF if fd is beyond the
// last preopen.
func (s *State) Xfd_prestat_get(fd, prestatPtr int32) int32 {
	idx := fd - 3
	if idx < 0 || idx >= int32(len(s.preopens)) {
		return wasiEBadf
	}
	mem := s.mem()
	pathLen := uint32(len(s.preopens[idx].path))
	binary.LittleEndian.PutUint32(mem[prestatPtr:], 0)
	binary.LittleEndian.PutUint32(mem[prestatPtr+4:], pathLen)
	return wasiESuccess
}
// Xfd_prestat_dir_name implements fd_prestat_dir_name. Writes the guest
// path string for the preopen directory at fd into guest memory.
func (s *State) Xfd_prestat_dir_name(fd, pathPtr, pathLen int32) int32 {
	idx := fd - 3
	if idx < 0 || idx >= int32(len(s.preopens)) {
		return wasiEBadf
	}
	mem := s.mem()
	name := s.preopens[idx].path
	copy(mem[pathPtr:], name)
	return wasiESuccess
}
// Xfd_fdstat_get implements fd_fdstat_get. Writes a 24-byte fdstat struct
// at statPtr. fds 0–2 are reported as character devices; all others use
// the type recorded in the fd table.
func (s *State) Xfd_fdstat_get(fd, statPtr int32) int32 {
	s.assertSingleOwner()
	if fd >= 0 && fd <= 2 {
		writeFdstat(s.mem(), statPtr, fdCharDev, rightsCharDev, rightsCharDev)
		return wasiESuccess
	}
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil && entry.fdType == 0 {
		return wasiEBadf
	}
	writeFdstat(s.mem(), statPtr, entry.fdType, rightsRegular, rightsRegular)
	return wasiESuccess
}

// writeFdstat writes a 24-byte WASI fdstat struct at statPtr in mem.
// Layout: fdtype(2) + flags(2) + padding(4) + rights_base(8) + rights_inheriting(8).
func writeFdstat(mem []byte, statPtr int32, fdType byte, rightsBase, rightsInheriting uint64) {
	var buf [24]byte
	binary.LittleEndian.PutUint16(buf[0:], uint16(fdType))
	binary.LittleEndian.PutUint16(buf[2:], 0)
	binary.LittleEndian.PutUint32(buf[4:], 0)
	binary.LittleEndian.PutUint64(buf[8:], rightsBase)
	binary.LittleEndian.PutUint64(buf[16:], rightsInheriting)
	copy(mem[statPtr:], buf[:])
}

// writeFilestat writes a 64-byte WASI filestat struct at bufPtr in mem.
// Layout: dev(8) + ino(8) + filetype(8) + nlink(8) + size(8) + atim(8) + mtim(8) + ctim(8).
// atim, mtim, and ctim are all set to mtimeNs; this host does not track
// separate access times.
func writeFilestat(mem []byte, bufPtr int32, fdType byte, size int64, mtimeNs int64) {
	var buf [64]byte
	binary.LittleEndian.PutUint64(buf[0:], 0)
	binary.LittleEndian.PutUint64(buf[8:], 0)
	binary.LittleEndian.PutUint64(buf[16:], uint64(fdType))
	binary.LittleEndian.PutUint64(buf[24:], 1)
	binary.LittleEndian.PutUint64(buf[32:], uint64(size))
	binary.LittleEndian.PutUint64(buf[40:], uint64(mtimeNs))
	binary.LittleEndian.PutUint64(buf[48:], uint64(mtimeNs))
	binary.LittleEndian.PutUint64(buf[56:], uint64(mtimeNs))
	copy(mem[bufPtr:], buf[:])
}

// Xfd_renumber implements fd_renumber. Copies the fd-table slot at fd to
// the slot at to and clears the source slot. Returns EBADF if either
// index is out of range.
func (s *State) Xfd_renumber(fd, to int32) int32 {
	s.assertSingleOwner()
	if fd < 0 || int(fd) >= len(s.fds) || to < 0 || int(to) >= len(s.fds) {
		return wasiEBadf
	}
	s.fds[to] = s.fds[fd]
	s.fds[fd] = fdEntry{}
	return wasiESuccess
}
// Xproc_exit implements proc_exit. Panics with [ExitError] so that the
// embedding application's eval boundary can recover it and obtain the
// guest exit code.
func (s *State) Xproc_exit(code int32) {
	panic(ExitError{Code: code})
}
// Xrandom_get implements random_get. Fills the guest memory region
// [bufPtr, bufPtr+bufLen) with cryptographically random bytes.
func (s *State) Xrandom_get(bufPtr, bufLen int32) int32 {
	mem := s.mem()
	rand.Read(mem[bufPtr : bufPtr+bufLen])
	return wasiESuccess
}

// Xclock_time_get implements clock_time_get. Writes the current time as
// a uint64 nanosecond value to resultPtr.
//
// clockID 0 (CLOCK_REALTIME): wall-clock time via time.Now().UnixNano().
// clockID 1 (CLOCK_MONOTONIC): nanoseconds elapsed since State construction.
// Any other clockID: returns ENOSYS.
func (s *State) Xclock_time_get(clockID int32, precision int64, resultPtr int32) int32 {
	mem := s.mem()
	switch clockID {
	case 0: // realtime
		binary.LittleEndian.PutUint64(mem[resultPtr:], uint64(time.Now().UnixNano()))
		return wasiESuccess
	case 1: // monotonic
		var t int64
		if s.startTime.IsZero() {
			t = time.Now().UnixNano()
		} else {
			t = time.Since(s.startTime).Nanoseconds()
		}
		binary.LittleEndian.PutUint64(mem[resultPtr:], uint64(t))
		return wasiESuccess
	default:
		return wasiENoSys
	}
}

// Xclock_res_get implements clock_res_get. Writes 1 (nanosecond
// resolution) for clockID 0 and 1. Returns ENOSYS for any other clockID.
func (s *State) Xclock_res_get(clockID int32, resultPtr int32) int32 {
	switch clockID {
	case 0, 1:
		binary.LittleEndian.PutUint64(s.mem()[resultPtr:], 1)
		return wasiESuccess
	default:
		return wasiENoSys
	}
}

// Xargs_sizes_get implements args_sizes_get. Writes the argument count
// and total buffer size (including null terminators) to guest memory.
func (s *State) Xargs_sizes_get(argcPtr, argvSizePtr int32) int32 {
	writeStringTableSizes(s.mem(), argcPtr, argvSizePtr, s.args)
	return wasiESuccess
}

// Xargs_get implements args_get. Writes a pointer array at argvPtr and
// the corresponding null-terminated argument strings packed at argvBufPtr
// into guest memory. Uses the same layout as environ_get.
func (s *State) Xargs_get(argvPtr, argvBufPtr int32) int32 {
	writeStringTable(s.mem(), argvPtr, argvBufPtr, s.args)
	return wasiESuccess
}

// readBytes reads length bytes from guest memory starting at ptr.
// Returns nil if ptr or length is zero.
func (s *State) readBytes(ptr, length int32) []byte {
	if ptr == 0 || length == 0 {
		return nil
	}
	return s.mem()[ptr : ptr+length]
}

// resolvePath resolves a guest-absolute path to the best-matching mount
// and a mount-relative path string using longest-prefix matching.
// Returns (nil, "") if no mount covers the path.
func (s *State) resolvePath(guestPath string) (*mountEntry, string) {
	var best *mountEntry
	bestLen := -1
	bestRel := ""
	for i := range s.mounts {
		m := &s.mounts[i]
		mp := path.Clean("/" + m.guestPath)
		if mp == "." {
			mp = "/"
		}

		clean := path.Clean("/" + guestPath)
		if clean == "." {
			clean = "/"
		}
		// Special case: if the path starts with the mount prefix but contains
		// ".." that would escape the mount, we still want to match the mount
		// but keep the ".." in rel.
		// resolvePath's use of path.Clean below collapses ".." before prefix
		// matching, which we bypass here if we find a raw prefix match.
		rawGuest := "/" + strings.TrimPrefix(guestPath, "/")
		rawMp := "/" + strings.TrimPrefix(m.guestPath, "/")
		if rawGuest == rawMp || strings.HasPrefix(rawGuest, rawMp+"/") {
			rel := strings.TrimPrefix(rawGuest, rawMp)
			rel = strings.TrimPrefix(rel, "/")
			if len(rawMp) > bestLen {
				best = m
				bestLen = len(rawMp)
				bestRel = rel
			}
			continue
		}

		match := false
		if clean == mp {
			match = true
		} else if mp == "/" {
			match = true
		} else if strings.HasPrefix(clean, mp+"/") {
			match = true
		}
		if !match {
			continue
		}
		rel := strings.TrimPrefix(clean, mp)
		rel = strings.TrimPrefix(rel, "/")
		if len(mp) > bestLen {
			best = m
			bestLen = len(mp)
			bestRel = rel
		}
	}
	return best, bestRel
}

// resolveDirfdPath resolves a WASI (dirfd, pathPtr, pathLen) triple to a
// mountEntry and a mount-relative path string.
//
// Absolute guest paths bypass dirfd and are resolved via resolvePath.
// For relative paths, preopen fds resolve directly against their mount.
// Non-preopen directory fds join the relative path against the absolute
// guest path stored in the fd entry, enabling correct nested path_open
// resolution during directory recursion.
func (s *State) resolveDirfdPath(dirfd, pathPtr, pathLen int32) (*mountEntry, string) {
	pathBytes := s.readBytes(pathPtr, pathLen)
	guestPath := string(pathBytes)
	if strings.HasPrefix(guestPath, "/") {
		return s.resolvePath(guestPath)
	}
	if dirfd >= 0 && int(dirfd) < len(s.fds) {
		entry := s.fds[dirfd]
		if entry.preopen && entry.mount >= 0 && entry.mount < len(s.mounts) {
			return &s.mounts[entry.mount], path.Clean(guestPath)
		}
		if entry.fdType == fdDir && entry.path != "" {
			full := path.Join(entry.path, guestPath)
			return s.resolvePath(full)
		}
	}
	return nil, ""
}

// isRootMount reports whether m covers the guest root directory "/".
func isRootMount(m *mountEntry) bool {
	return path.Clean("/"+m.guestPath) == "/"
}

// mountHostPaths returns the primary and fallback host filesystem paths
// for a mount-relative path rel within mount m. Returns ("", "") if m is
// nil, not writable, or has no hostRoot.
//
// For root mounts the primary path is the re-absolutized form
// ("/" + rel), recovering the original absolute host path that the WASI
// libc stripped when mapping guest paths to the "/" preopen fd. If that
// path differs from filepath.Join(hostRoot, rel), the joined form is
// returned as fallback for cwd-relative paths.
// For non-root mounts only the joined path is returned as primary.
func mountHostPaths(m *mountEntry, rel string) (primary, fallback string) {
	if m == nil || !m.writable || m.hostRoot == "" {
		return "", ""
	}
	joined := filepath.Join(m.hostRoot, filepath.FromSlash(rel))
	if isRootMount(m) {
		abs := "/" + filepath.FromSlash(rel)
		if abs != joined {
			return abs, joined
		}
	}
	return joined, ""
}

// resolvePrimary is a convenience wrapper that resolves a (dirfd, path)
// pair to a single primary host path. Returns "" if the path resolves to
// a read-only or unmounted location.
func (s *State) resolvePrimary(dirfd, pathPtr, pathLen int32) string {
	m, rel := s.resolveDirfdPath(dirfd, pathPtr, pathLen)
	if m == nil {
		return ""
	}
	primary, _ := mountHostPaths(m, rel)
	return primary
}

// resolveWritable resolves a (dirfd, path) pair to a host path, choosing
// between primary and fallback based on existence. This is used for
// mutation operations where relative paths on a root writable mount
// should fall back to the hostRoot.
func (s *State) resolveWritable(dirfd, pathPtr, pathLen int32) (string, int32) {
	m, rel := s.resolveDirfdPath(dirfd, pathPtr, pathLen)
	if m == nil {
		if dirfd < 0 || int(dirfd) >= len(s.fds) {
			return "", wasiEBadf
		}
		// Existing behavior from TestWASIStubs/TestXpathRename
		return "", wasiEROFS
	}
	primary, fallback := mountHostPaths(m, rel)
	if primary == "" {
		return "", wasiEROFS
	}
	if fallback != "" {
		if _, err := os.Stat(primary); err != nil {
			return fallback, wasiESuccess
		}
	}
	return primary, wasiESuccess
}

// Xpath_create_directory implements path_create_directory. Creates a
// directory at the resolved host path via os.Mkdir. Returns EROFS if the
// mount is read-only, EEXIST if the directory already exists, ENOENT if
// the parent does not exist.
func (s *State) Xpath_create_directory(dirfd, pathPtr, pathLen int32) int32 {
	path, errno := s.resolveWritable(dirfd, pathPtr, pathLen)
	if errno != wasiESuccess {
		return errno
	}
	if err := os.Mkdir(path, 0755); err != nil {
		return mapOSError(err)
	}
	return wasiESuccess
}

// Xpath_remove_directory implements path_remove_directory. Removes an
// empty directory at the resolved host path. Returns EROFS if the mount
// is read-only, ENOTDIR if the target is a file, ENOTEMPTY if the
// directory is not empty.
func (s *State) Xpath_remove_directory(dirfd, pathPtr, pathLen int32) int32 {
	path, errno := s.resolveWritable(dirfd, pathPtr, pathLen)
	if errno != wasiESuccess {
		return errno
	}
	fi, err := os.Lstat(path)
	if err != nil {
		return mapOSError(err)
	}
	if !fi.IsDir() {
		return wasiENotDir
	}
	if err := os.Remove(path); err != nil {
		return mapOSError(err)
	}
	return wasiESuccess
}

// Xpath_unlink_file implements path_unlink_file. Removes a file at the
// resolved host path. Returns EROFS if the mount is read-only, EISDIR if
// the target is a directory, ENOENT if the file does not exist.
func (s *State) Xpath_unlink_file(dirfd, pathPtr, pathLen int32) int32 {
	path, errno := s.resolveWritable(dirfd, pathPtr, pathLen)
	if errno != wasiESuccess {
		return errno
	}
	fi, err := os.Lstat(path)
	if err != nil {
		return mapOSError(err)
	}
	if fi.IsDir() {
		return wasiEIsdir
	}
	if err := os.Remove(path); err != nil {
		return mapOSError(err)
	}
	return wasiESuccess
}

// Xpath_readlink implements path_readlink. Reads the target of a symbolic
// link at the resolved host path into guest memory at bufPtr, capped at
// bufLen bytes, and writes the actual byte count to nreadPtr. Returns
// EROFS if the mount is read-only (embedded fs.FS mounts have no symlinks).
func (s *State) Xpath_readlink(dirfd, pathPtr, pathLen, bufPtr, bufLen, nreadPtr int32) int32 {
	path, errno := s.resolveWritable(dirfd, pathPtr, pathLen)
	if errno != wasiESuccess {
		return errno
	}
	target, err := os.Readlink(path)
	if err != nil {
		return mapOSError(err)
	}
	mem := s.mem()
	n := copy(mem[bufPtr:bufPtr+bufLen], target)
	binary.LittleEndian.PutUint32(mem[nreadPtr:], uint32(n))
	return wasiESuccess
}

// Xpath_symlink implements path_symlink. Creates a symbolic link at the
// resolved host path for newPath pointing to the raw string oldPath.
// Returns EROFS if the mount is read-only, EEXIST if the link path already
// exists.
func (s *State) Xpath_symlink(oldPathPtr, oldPathLen, dirfd, newPathPtr, newPathLen int32) int32 {
	target := string(s.readBytes(oldPathPtr, oldPathLen))
	path, errno := s.resolveWritable(dirfd, newPathPtr, newPathLen)
	if errno != wasiESuccess {
		return errno
	}
	if err := os.Symlink(target, path); err != nil {
		return mapOSError(err)
	}
	return wasiESuccess
}

// Xpath_link implements path_link. Creates a hard link from the resolved
// old path to the resolved new path via os.Link. Returns EROFS if either
// mount is read-only.
func (s *State) Xpath_link(oldDirfd, oldFlags, oldPathPtr, oldPathLen, newDirfd, newPathPtr, newPathLen int32) int32 {
	oldPath, oldErr := s.resolveWritable(oldDirfd, oldPathPtr, oldPathLen)
	if oldErr != wasiESuccess {
		return oldErr
	}
	newPath, newErr := s.resolveWritable(newDirfd, newPathPtr, newPathLen)
	if newErr != wasiESuccess {
		return newErr
	}
	if err := os.Link(oldPath, newPath); err != nil {
		return mapOSError(err)
	}
	return wasiESuccess
}

// Xfd_close implements fd_close. Closes the file associated with fd and
// clears the fd-table slot. Returns EBADF if fd is invalid or a preopen
// directory fd (preopen fds cannot be closed).
func (s *State) Xfd_close(fd int32) int32 {
	s.assertSingleOwner()
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	if s.fds[fd].preopen {
		return wasiEBadf
	}
	if s.fds[fd].file == nil && s.fds[fd].fdType == 0 {
		return wasiEBadf
	}
	if s.fds[fd].file != nil {
		s.fds[fd].file.Close()
	}
	s.fds[fd] = fdEntry{}
	return wasiESuccess
}

// Xfd_read implements fd_read. For fd 0 (stdin), reads from the
// io.Reader configured by [WithStdin]. For other fds, uses ReadAt when
// the underlying file supports it (osFile) to keep the WASI-level offset
// in sync with WriteAt calls; falls back to Read for fs.FS-backed files.
func (s *State) Xfd_read(fd int32, iovsPtr int32, iovsCount int32, nreadPtr int32) int32 {
	s.assertSingleOwner()
	mem := s.mem()
	if fd == 0 {
		var total uint32
		for i := int32(0); i < iovsCount; i++ {
			off := iovsPtr + i*8
			bufPtr := int32(binary.LittleEndian.Uint32(mem[off:]))
			bufLen := int32(binary.LittleEndian.Uint32(mem[off+4:]))
			if bufLen == 0 {
				continue
			}
			var n int
			var err error
			if s.stdin != nil {
				n, err = s.stdin.Read(mem[bufPtr : bufPtr+bufLen])
			} else {
				n, err = 0, io.EOF
			}
			total += uint32(n)
			if err != nil {
				binary.LittleEndian.PutUint32(mem[nreadPtr:], total)
				if err != io.EOF {
					return wasiEIo
				}
				return wasiESuccess
			}
			if n < int(bufLen) {
				break
			}
		}
		binary.LittleEndian.PutUint32(mem[nreadPtr:], total)
		return wasiESuccess
	}
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil {
		return wasiEBadf
	}
	var total uint32
	for i := int32(0); i < iovsCount; i++ {
		off := iovsPtr + i*8
		bufPtr := int32(binary.LittleEndian.Uint32(mem[off:]))
		bufLen := int32(binary.LittleEndian.Uint32(mem[off+4:]))
		if bufLen == 0 {
			continue
		}
		var n int
		var err error
		if ra, ok := entry.file.(interface {
			ReadAt([]byte, int64) (int, error)
		}); ok {
			n, err = ra.ReadAt(mem[bufPtr:bufPtr+bufLen], entry.offset)
		} else {
			n, err = entry.file.Read(mem[bufPtr : bufPtr+bufLen])
		}
		total += uint32(n)
		entry.offset += int64(n)
		if err != nil {
			if err == io.EOF {
				break
			}
			s.fds[fd] = entry
			binary.LittleEndian.PutUint32(mem[nreadPtr:], total)
			return wasiEIo
		}
		if n < int(bufLen) {
			break
		}
	}
	s.fds[fd] = entry
	binary.LittleEndian.PutUint32(mem[nreadPtr:], total)
	return wasiESuccess
}

// Xfd_write implements fd_write. For fd 1 and 2 (stdout/stderr), writes
// to the io.Writers configured by [WithStdout] and [WithStderr]. For
// other fds, uses WriteAt with the current fd offset; only osFile-backed
// entries support writes.
func (s *State) Xfd_write(fd int32, iovsPtr int32, iovsCount int32, nwrittenPtr int32) int32 {
	s.assertSingleOwner()
	mem := s.mem()
	if fd == 1 || fd == 2 {
		var total uint32
		for i := int32(0); i < iovsCount; i++ {
			off := iovsPtr + i*8
			bufPtr := int32(binary.LittleEndian.Uint32(mem[off:]))
			bufLen := int32(binary.LittleEndian.Uint32(mem[off+4:]))
			data := mem[bufPtr : bufPtr+bufLen]
			var n int
			var err error
			if fd == 1 {
				if s.stdout != nil {
					n, err = s.stdout.Write(data)
				}
			} else {
				if s.stderr != nil {
					n, err = s.stderr.Write(data)
				}
			}
			total += uint32(n)
			if err != nil {
				binary.LittleEndian.PutUint32(mem[nwrittenPtr:], total)
				return wasiEIo
			}
		}
		binary.LittleEndian.PutUint32(mem[nwrittenPtr:], total)
		return wasiESuccess
	}
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil {
		return wasiEBadf
	}
	var total uint32
	for i := int32(0); i < iovsCount; i++ {
		off := iovsPtr + i*8
		bufPtr := int32(binary.LittleEndian.Uint32(mem[off:]))
		bufLen := int32(binary.LittleEndian.Uint32(mem[off+4:]))
		if bufLen == 0 {
			continue
		}
		wa, ok := entry.file.(interface {
			WriteAt([]byte, int64) (int, error)
		})
		if !ok {
			break
		}
		n, err := wa.WriteAt(mem[bufPtr:bufPtr+bufLen], entry.offset)
		entry.offset += int64(n)
		total += uint32(n)
		if err != nil {
			s.fds[fd] = entry
			binary.LittleEndian.PutUint32(mem[nwrittenPtr:], total)
			return wasiEIo
		}
	}
	s.fds[fd] = entry
	binary.LittleEndian.PutUint32(mem[nwrittenPtr:], total)
	return wasiESuccess
}

// Xfd_seek implements fd_seek. Delegates to the underlying io.Seeker and
// updates the WASI-level fd offset so that subsequent fd_write (via
// WriteAt) and fd_tell return consistent positions. Returns EISDIR for
// directory fds, EINVAL if the file does not implement io.Seeker.
func (s *State) Xfd_seek(fd int32, offset int64, whence, newOffsetPtr int32) int32 {
	s.assertSingleOwner()
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil || entry.preopen {
		return wasiEBadf
	}
	if entry.fdType == fdDir {
		return wasiEIsdir
	}
	sk, ok := entry.file.(io.Seeker)
	if !ok {
		return wasiEInval
	}
	n, err := sk.Seek(offset, int(whence))
	if err != nil {
		return wasiEIo
	}
	entry.offset = n
	s.fds[fd] = entry
	binary.LittleEndian.PutUint64(s.mem()[newOffsetPtr:], uint64(n))
	return wasiESuccess
}

// Xfd_readdir implements fd_readdir. Writes WASI dirent structs into
// guest memory starting from the entry at cookie. Each dirent is
// 24 + len(name) bytes. For preopen fds backed by fs.ReadDirFS, the
// directory listing is loaded on first call and cached in the fd entry.
func (s *State) Xfd_readdir(fd int32, bufPtr int32, bufLen int32, cookie int64, bufUsedPtr int32) int32 {
	s.assertSingleOwner()
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := &s.fds[fd]
	mem := s.mem()
	// Cache listing on first call for preopens or any directory fd.
	if entry.dirFile == nil {
		if entry.preopen {
			if entry.mount < 0 || entry.mount >= len(s.mounts) {
				return wasiEBadf
			}
			if entry.file == nil {
				if d, ok := s.mounts[entry.mount].root.(fs.ReadDirFS); ok {
					entries, err := d.ReadDir(".")
					if err != nil {
						return wasiEIo
					}
					entry.file = &DirEntriesFile{Entries: entries}
				}
			}
		}
		if entry.file == nil {
			return wasiEBadf
		}
		df, ok := entry.file.(fs.ReadDirFile)
		if !ok {
			return wasiENotDir
		}
		entry.dirFile = df
	}

	entries, err := entry.dirFile.ReadDir(-1)
	if err != nil && err != io.EOF {
		return wasiEIo
	}
	// Restore entries to the file if it's our own DirEntriesFile adapter,
	// so that subsequent calls with cookies can still access them.
	if de, ok := entry.file.(*DirEntriesFile); ok {
		de.idx = 0
	}

	if cookie > 0 && int(cookie) >= len(entries) {
		binary.LittleEndian.PutUint32(mem[bufUsedPtr:], 0)
		return wasiESuccess
	}
	if len(entries) == 0 {
		binary.LittleEndian.PutUint32(mem[bufUsedPtr:], 0)
		return wasiESuccess
	}
	var dUsed uint32
	for i := int(cookie); i < len(entries); i++ {
		name := entries[i].Name()
		dNameLen := uint32(len(name))
		dEntryLen := uint32(24 + dNameLen)
		if dUsed+dEntryLen > uint32(bufLen) {
			break
		}
		off := bufPtr + int32(dUsed)
		binary.LittleEndian.PutUint64(mem[off:], uint64(i+1))
		binary.LittleEndian.PutUint64(mem[off+8:], 0)
		binary.LittleEndian.PutUint32(mem[off+16:], dNameLen)
		var ftype byte
		if entries[i].IsDir() {
			ftype = fdDir
		} else {
			ftype = fdFile
		}
		binary.LittleEndian.PutUint32(mem[off+20:], uint32(ftype))
		copy(mem[off+24:], name)
		dUsed += dEntryLen
	}
	binary.LittleEndian.PutUint32(mem[bufUsedPtr:], dUsed)
	return wasiESuccess
}

// Xfd_filestat_get implements fd_filestat_get. Writes a 64-byte filestat
// struct for the open fd. For preopen directory fds, stats the mount root
// via fs.Stat.
func (s *State) Xfd_filestat_get(fd, bufPtr int32) int32 {
	s.assertSingleOwner()
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.preopen {
		if entry.mount < 0 || entry.mount >= len(s.mounts) {
			return wasiEBadf
		}
		fi, err := fs.Stat(s.mounts[entry.mount].root, ".")
		if err != nil {
			return wasiEIo
		}
		writeFilestat(s.mem(), bufPtr, fdDir, fi.Size(), fi.ModTime().UnixNano())
		return wasiESuccess
	}
	if entry.file == nil {
		return wasiEBadf
	}
	fi, err := entry.file.Stat()
	if err != nil {
		return wasiEIo
	}
	writeFilestat(s.mem(), bufPtr, entry.fdType, fi.Size(), fi.ModTime().UnixNano())
	return wasiESuccess
}

// Xpath_filestat_get implements path_filestat_get. Resolves the path and
// writes a 64-byte filestat struct. For writable mounts, tries os.Stat
// first (with primary/fallback resolution), then falls back to the
// overlay fs.FS for embedded files.
func (s *State) Xpath_filestat_get(dirfd, flags, pathPtr, pathLen, bufPtr int32) int32 {
	mount, relPath := s.resolveDirfdPath(dirfd, pathPtr, pathLen)
	if mount == nil {
		return wasiENoEnt
	}
	var fi fs.FileInfo
	if mount.writable && mount.hostRoot != "" {
		primary, cwdFallback := mountHostPaths(mount, relPath)
		var osErr error
		fi, osErr = os.Stat(primary)
		if osErr != nil && cwdFallback != "" {
			fi, osErr = os.Stat(cwdFallback)
		}
		if osErr != nil {
			var fsErr error
			fi, fsErr = fs.Stat(mount.root, relPath)
			if fsErr != nil {
				return wasiENoEnt
			}
		}
	} else {
		var fsErr error
		fi, fsErr = fs.Stat(mount.root, relPath)
		if fsErr != nil {
			return wasiENoEnt
		}
	}
	fdType := fdFile
	if fi.IsDir() {
		fdType = fdDir
	}
	writeFilestat(s.mem(), bufPtr, fdType, fi.Size(), fi.ModTime().UnixNano())
	return wasiESuccess
}

// Xpath_open implements path_open. Resolves the guest path and allocates
// a new fd. For writable mounts, opens via os.OpenFile using oflags and
// fdRightsBase to determine OS open flags; falls back to the overlay
// fs.FS for read-only opens that do not create or truncate. The special
// path "/dev/null" is handled as a character-device fd without mount
// resolution. Absolute guest paths stored on directory fds enable correct
// nested resolution during directory recursion.
func (s *State) Xpath_open(dirfd int32, lookupFlags int32, pathPtr int32, pathLen int32, oflags int32, fdRightsBase int64, fdRightsInheriting int64, fdFlags int32, fdPtr int32) int32 {
	s.assertSingleOwner()
	pathBytes := s.readBytes(pathPtr, pathLen)
	guestPath := string(pathBytes)
	mem := s.mem()
	if guestPath == "/dev/null" {
		fd := s.allocFD()
		s.fds[fd] = fdEntry{fdType: fdCharDev, path: "/dev/null"}
		binary.LittleEndian.PutUint32(mem[fdPtr:], uint32(fd))
		return wasiESuccess
	}
	mount, relPath := s.resolveDirfdPath(dirfd, pathPtr, pathLen)
	if mount == nil {
		return wasiENoEnt
	}
	var f fs.File
	var err error
	if mount.writable {
		primary, cwdFallback := mountHostPaths(mount, relPath)
		if primary == "" {
			primary = relPath
		}
		hostPath := primary
		osFlags := os.O_RDONLY
		if (uint64(fdRightsBase)&rightFDWrite) != 0 || (uint32(oflags)&(oflagCreat|oflagTrunc|oflagExcl)) != 0 {
			osFlags = os.O_RDWR
		}
		if uint32(oflags)&oflagCreat != 0 {
			osFlags |= os.O_CREATE
		}
		if uint32(oflags)&oflagTrunc != 0 {
			osFlags |= os.O_TRUNC
		}
		if uint32(oflags)&oflagExcl != 0 {
			osFlags |= os.O_EXCL
		}
		if uint32(oflags)&oflagDir != 0 {
			osFlags = os.O_RDONLY
		}
		hostFile, osErr := os.OpenFile(hostPath, osFlags, 0o666)
		if osErr != nil && cwdFallback != "" {
			hostFile, osErr = os.OpenFile(cwdFallback, osFlags, 0o666)
		}
		if osErr != nil {
			if uint32(oflags)&(oflagCreat|oflagTrunc|oflagExcl) == 0 {
				f, err = mount.root.Open(relPath)
				if err != nil {
					return wasiENoEnt
				}
				fi, _ := f.Stat()
				fdType := fdFile
				if fi != nil && fi.IsDir() {
					fdType = fdDir
				}
				fd := s.allocFD()
				entryPath := guestPath
				if fdType == fdDir {
					entryPath = path.Clean("/" + mount.guestPath + "/" + relPath)
				}
				entry := fdEntry{file: &FSFileWrap{File: f}, path: entryPath, fdType: fdType}
				if fdType == fdDir {
					if df, ok := f.(fs.ReadDirFile); ok {
						entry.dirFile = df
					}
				}
				s.fds[fd] = entry
				binary.LittleEndian.PutUint32(mem[fdPtr:], uint32(fd))
				return wasiESuccess
			}
			return wasiENoEnt
		}
		fi, _ := hostFile.Stat()
		fd := s.allocFD()
		entryPath := guestPath
		if fi != nil && fi.IsDir() {
			entryPath = path.Clean("/" + mount.guestPath + "/" + relPath)
		}
		s.fds[fd] = fdEntry{file: &osFile{File: hostFile}, path: entryPath, fdType: fdFile}
		if fi != nil && fi.IsDir() {
			s.fds[fd].fdType = fdDir
		}
		binary.LittleEndian.PutUint32(mem[fdPtr:], uint32(fd))
		return wasiESuccess
	}
	f, err = mount.root.Open(relPath)
	if err != nil {
		return wasiENoEnt
	}
	fi, _ := f.Stat()
	fdType := fdFile
	if fi != nil && fi.IsDir() {
		fdType = fdDir
	}
	fd := s.allocFD()
	savedPath := guestPath
	if !strings.HasPrefix(savedPath, "/") {
		if dirfd >= 0 && int(dirfd) < len(s.fds) {
			parent := s.fds[dirfd]
			if parent.path != "" {
				savedPath = path.Join(parent.path, guestPath)
			}
		}
	}
	entry := fdEntry{file: &FSFileWrap{File: f}, path: savedPath, fdType: fdType}
	if fdType == fdDir {
		if df, ok := f.(fs.ReadDirFile); ok {
			entry.dirFile = df
		}
	}
	s.fds[fd] = entry
	binary.LittleEndian.PutUint32(mem[fdPtr:], uint32(fd))
	return wasiESuccess
}

// Xpath_rename implements path_rename. Resolves both old and new paths
// and calls os.Rename. Uses primary/fallback resolution for root mounts:
// if the primary (re-absolutized) path does not exist, retries with the
// cwd-joined fallback. Returns EROFS if either mount is read-only.
func (s *State) Xpath_rename(oldDirfd, oldPathPtr, oldPathLen, newDirfd, newPathPtr, newPathLen int32) int32 {
	oldMount, oldRel := s.resolveDirfdPath(oldDirfd, oldPathPtr, oldPathLen)
	newMount, newRel := s.resolveDirfdPath(newDirfd, newPathPtr, newPathLen)
	if oldMount == nil || newMount == nil {
		return wasiENoEnt
	}
	oldPrimary, oldFallback := mountHostPaths(oldMount, oldRel)
	newPrimary, newFallback := mountHostPaths(newMount, newRel)
	if oldPrimary == "" || newPrimary == "" {
		return wasiEROFS
	}
	if oldFallback != "" {
		if _, err := os.Stat(oldPrimary); err != nil {
			oldPrimary, newPrimary = oldFallback, newFallback
		}
	}
	if err := os.Rename(oldPrimary, newPrimary); err != nil {
		return wasiEIo
	}
	return wasiESuccess
}

// Xpoll_oneoff implements poll_oneoff. Clock subscriptions (event type 0)
// are handled by sleeping for the shortest requested timeout nanoseconds.
// fd_read and fd_write subscriptions (event types 1 and 2) validate fd
// existence but do not model actual I/O readiness. A real readiness model
// would require async I/O infrastructure beyond this synchronous host's
// scope.
func (s *State) Xpoll_oneoff(inPtr int32, outPtr int32, nsubscriptions int32, neventsPtr int32) int32 {
	s.assertSingleOwner()
	mem := s.mem()
	var minTimeout int64 = -1
	for i := int32(0); i < nsubscriptions; i++ {
		subOff := inPtr + i*48
		userdata := binary.LittleEndian.Uint64(mem[subOff:])
		eventType := binary.LittleEndian.Uint32(mem[subOff+40:])
		var errno uint32 = 0
		switch eventType {
		case 0: // clock
			timeout := int64(binary.LittleEndian.Uint64(mem[subOff+8+8:]))
			if timeout > 0 && (minTimeout < 0 || timeout < minTimeout) {
				minTimeout = timeout
			}
		case 1: // fd_read
			fd := int32(binary.LittleEndian.Uint32(mem[subOff+8:]))
			if fd < 0 || fd >= int32(len(s.fds)) {
				errno = uint32(wasiEBadf)
			}
		case 2: // fd_write
			fd := int32(binary.LittleEndian.Uint32(mem[subOff+8:]))
			if fd < 0 || fd >= int32(len(s.fds)) {
				errno = uint32(wasiEBadf)
			}
		}
		evOff := outPtr + i*32
		binary.LittleEndian.PutUint64(mem[evOff:], userdata)
		binary.LittleEndian.PutUint16(mem[evOff+8:], uint16(errno))
		binary.LittleEndian.PutUint16(mem[evOff+10:], 0)
		binary.LittleEndian.PutUint32(mem[evOff+12:], eventType)
		binary.LittleEndian.PutUint64(mem[evOff+16:], 0)
		binary.LittleEndian.PutUint64(mem[evOff+24:], 0)
	}
	if minTimeout > 0 {
		time.Sleep(time.Duration(minTimeout))
	}
	binary.LittleEndian.PutUint32(mem[neventsPtr:], uint32(nsubscriptions))
	return wasiESuccess
}

// Xcall_host_function implements the env.call_host_function import used
// by zeroperl-style wasm2go modules as a host-callback bridge. This host
// does not support guest-initiated host callbacks; it always returns 0.
func (s *State) Xcall_host_function(v0, v1, v2 int32) int32 { return 0 }

// writeStringTableSizes writes the item count and total buffer size
// (sum of len(item)+1 for each item) to countPtr and bufSizePtr in mem.
// Shared by environ_sizes_get and args_sizes_get.
func writeStringTableSizes(mem []byte, countPtr, bufSizePtr int32, items []string) {
	binary.LittleEndian.PutUint32(mem[countPtr:], uint32(len(items)))
	var total uint32
	for _, s := range items {
		total += uint32(len(s)) + 1
	}
	binary.LittleEndian.PutUint32(mem[bufSizePtr:], total)
}

// writeStringTable writes a pointer array at ptrBase and null-terminated
// strings packed at bufBase into mem. Each pointer is a uint32 offset into
// mem pointing to the start of the corresponding string. Shared by
// environ_get and args_get.
func writeStringTable(mem []byte, ptrBase, bufBase int32, items []string) {
	bufOff := uint32(bufBase)
	for i, s := range items {
		binary.LittleEndian.PutUint32(mem[ptrBase+int32(i*4):], bufOff)
		n := copy(mem[bufOff:], s)
		mem[bufOff+uint32(n)] = 0
		bufOff += uint32(n) + 1
	}
}

// Xfd_pread implements fd_pread. Reads from fd at the given offset
// without updating the fd's WASI-level offset (entry.offset). Requires
// the underlying file to implement ReadAt; if it does not, no bytes are
// read. Returns EINVAL for fds 0–2 (positioned reads on stdio are not
// defined by WASI).
func (s *State) Xfd_pread(fd, iovsPtr, iovsCount int32, offset int64, nreadPtr int32) int32 {
	if fd <= 2 {
		return wasiEInval
	}
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil {
		return wasiEBadf
	}
	mem := s.mem()
	var total uint32
	curOff := offset
	for i := int32(0); i < iovsCount; i++ {
		off := iovsPtr + i*8
		bufPtr := int32(binary.LittleEndian.Uint32(mem[off:]))
		bufLen := int32(binary.LittleEndian.Uint32(mem[off+4:]))
		if bufLen == 0 {
			continue
		}
		var n int
		var err error
		ra, ok := entry.file.(interface {
			ReadAt([]byte, int64) (int, error)
		})
		if !ok {
			binary.LittleEndian.PutUint32(mem[nreadPtr:], total)
			return wasiENotSup
		}
		n, err = ra.ReadAt(mem[bufPtr:bufPtr+bufLen], curOff)
		total += uint32(n)
		curOff += int64(n)
		if err != nil {
			break
		}
	}
	binary.LittleEndian.PutUint32(mem[nreadPtr:], total)
	return wasiESuccess
}

// Xfd_pwrite implements fd_pwrite. Writes to fd at the given offset
// without updating the fd's WASI-level offset (entry.offset). Requires
// the underlying file to implement WriteAt; if it does not, no bytes are
// written. Returns EINVAL for fds 0–2 (positioned writes on stdio are
// not defined by WASI).
func (s *State) Xfd_pwrite(fd, iovsPtr, iovsCount int32, offset int64, nwrittenPtr int32) int32 {
	if fd <= 2 {
		return wasiEInval
	}
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil {
		return wasiEBadf
	}
	mem := s.mem()
	var total uint32
	curOff := offset
	for i := int32(0); i < iovsCount; i++ {
		off := iovsPtr + i*8
		bufPtr := int32(binary.LittleEndian.Uint32(mem[off:]))
		bufLen := int32(binary.LittleEndian.Uint32(mem[off+4:]))
		if bufLen == 0 {
			continue
		}
		wa, ok := entry.file.(interface {
			WriteAt([]byte, int64) (int, error)
		})
		if !ok {
			binary.LittleEndian.PutUint32(mem[nwrittenPtr:], total)
			return wasiENotSup
		}
		n, err := wa.WriteAt(mem[bufPtr:bufPtr+bufLen], curOff)
		total += uint32(n)
		curOff += int64(n)
		if err != nil {
			break
		}
	}
	binary.LittleEndian.PutUint32(mem[nwrittenPtr:], total)
	return wasiESuccess
}

// Xfd_tell implements fd_tell. Returns the WASI-level fd offset
// (entry.offset) rather than the kernel file position. This is necessary
// because fd_write uses WriteAt, which does not advance the kernel
// position; reading it back via Seek(0, SeekCurrent) would return a
// stale value.
func (s *State) Xfd_tell(fd, offsetPtr int32) int32 {
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil && entry.fdType == 0 {
		return wasiEBadf
	}
	binary.LittleEndian.PutUint64(s.mem()[offsetPtr:], uint64(entry.offset))
	return wasiESuccess
}

// Xsched_yield implements sched_yield. Returns ESUCCESS.
func (s *State) Xsched_yield() int32 { return wasiESuccess }

// Xfd_datasync implements fd_datasync. Returns ESUCCESS without calling
// Sync on the underlying file. A future version may call
// (*os.File).Sync for osFile-backed fds.
func (s *State) Xfd_datasync(fd int32) int32 { return wasiESuccess }

// Xfd_sync implements fd_sync. Always returns ESUCCESS without calling
// Sync on the underlying file. Embedded fs.FS files have no sync
// semantics, and ExifTool does not issue fd_sync in practice.
func (s *State) Xfd_sync(fd int32) int32 { return wasiESuccess }

// Xfd_fdstat_set_flags implements fd_fdstat_set_flags. Always returns
// ESUCCESS. Non-blocking I/O flags have no meaning in a synchronous
// wasm2go host; this is an intentional no-op.
func (s *State) Xfd_fdstat_set_flags(fd, flags int32) int32 { return wasiESuccess }

// Xfd_advise implements fd_advise (POSIX posix_fadvise). Always returns
// ESUCCESS. There is no portable Go equivalent for this hint; it is
// silently ignored.
func (s *State) Xfd_advise(fd int32, offset, length int64, advice int32) int32 { return wasiESuccess }

// Xfd_allocate implements fd_allocate (fallocate). Always returns ESUCCESS.
// Disk-space pre-reservation is advisory; this is an intentional no-op.
func (s *State) Xfd_allocate(fd int32, offset, length int64) int32 { return wasiESuccess }

// Xfd_fdstat_set_rights implements fd_fdstat_set_rights. Always returns
// ESUCCESS. Capability rights narrowing is not enforced in this host.
func (s *State) Xfd_fdstat_set_rights(fd int32, base, inheriting int64) int32 { return wasiESuccess }

// Xproc_raise implements proc_raise. Always returns ENOSYS. Raising a
// signal inside a WASM guest has no meaningful host mapping.
func (s *State) Xproc_raise(signal int32) int32 { return wasiENoSys }

// Xsock_accept, Xsock_recv, Xsock_send, and Xsock_shutdown implement the
// WASI socket functions. All return ENOSYS; sockets are not supported in
// this host.
func (s *State) Xsock_accept(fd, flags, resultPtr int32) int32 { return wasiENoSys }
func (s *State) Xsock_recv(fd, iovsPtr, iovsLen, riFlags, nreadPtr, roFlagsPtr int32) int32 {
	return wasiENoSys
}
func (s *State) Xsock_send(fd, iovsPtr, iovsLen, siFlags, nsentPtr int32) int32 { return wasiENoSys }
func (s *State) Xsock_shutdown(fd, how int32) int32                             { return wasiENoSys }

// Xfd_filestat_set_size implements fd_filestat_set_size. For osFile-backed
// fds, truncates the file to size bytes via (*os.File).Truncate. For
// fs.FS-backed fds, returns ESUCCESS without mutation (embedded files are
// read-only by construction).
func (s *State) Xfd_filestat_set_size(fd int32, size int64) int32 {
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.fdType == 0 {
		return wasiEBadf
	}
	if of, ok := entry.file.(*osFile); ok {
		if err := of.Truncate(size); err != nil {
			return mapOSError(err)
		}
	}
	return wasiESuccess
}
// Xfd_filestat_set_times implements fd_filestat_set_times.
// fstFlags:
// - bit 0 (1): ATIM (not implemented)
// - bit 1 (2): MTIM
// - bit 2 (4): ATIM_NOW (not implemented)
// - bit 3 (8): MTIM_NOW
//
// For osFile-backed fds, calls os.Chtimes with the specified mtim
// nanosecond value or the current time if MTIM_NOW is set. For
// fs.FS-backed fds, returns ESUCCESS without mutation.
func (s *State) Xfd_filestat_set_times(fd int32, atim, mtim int64, fstFlags int32) int32 {
	if fstFlags&10 == 0 { // MTIM | MTIM_NOW
		return wasiESuccess
	}
	if fd < 0 || int(fd) >= len(s.fds) {
		return wasiEBadf
	}
	entry := s.fds[fd]
	if entry.file == nil {
		return wasiEBadf
	}
	if of, ok := entry.file.(*osFile); ok {
		targetMtim := mtim
		if fstFlags&8 != 0 {
			targetMtim = time.Now().UnixNano()
		}
		return applyMtim(of.Name(), targetMtim)
	}
	return wasiESuccess
}
// Xpath_filestat_set_times implements path_filestat_set_times. Only the
// MTIM flag (bit 1) is currently acted upon; if it is not set the call is
// a no-op. Resolves the path and calls os.Chtimes. Returns ESUCCESS
// without mutation for read-only mounts.
func (s *State) Xpath_filestat_set_times(dirfd, flags, pathPtr, pathLen int32, atim, mtim int64, fstFlags int32) int32 {
	if fstFlags&2 == 0 {
		return wasiESuccess
	}
	primary := s.resolvePrimary(dirfd, pathPtr, pathLen)
	if primary == "" {
		return wasiEROFS
	}
	return applyMtim(primary, mtim)
}

// applyMtim calls os.Chtimes to set the mtime of the file at path to the
// given nanosecond timestamp. atime is set to the current wall time as a
// neutral value. Returns the mapped WASI errno on failure.
func applyMtim(path string, mtim int64) int32 {
	mtime := time.Unix(0, mtim)
	atime := time.Now()
	if err := os.Chtimes(path, atime, mtime); err != nil {
		return mapOSError(err)
	}
	return wasiESuccess
}

// mapOSError converts a host OS error to the closest WASI errno value.
// Canonical mappings: ErrNotExist→ENOENT(44), ErrExist→EEXIST(20),
// ENOTEMPTY→ENOTEMPTY(55). All other errors map to EIO(29).
func mapOSError(err error) int32 {
	if errors.Is(err, os.ErrNotExist) {
		return wasiENoEnt
	}
	if errors.Is(err, syscall.ENOTEMPTY) {
		return wasiENotEmpty
	}
	if errors.Is(err, os.ErrExist) {
		return wasiEExist
	}
	if errors.Is(err, syscall.ENOTDIR) {
		return wasiENotDir
	}
	if errors.Is(err, syscall.EISDIR) {
		return wasiEIsdir
	}
	if errors.Is(err, syscall.EACCES) {
		return wasiEAcces
	}
	if errors.Is(err, syscall.EPERM) {
		return wasiEPerm
	}
	if errors.Is(err, syscall.EROFS) {
		return wasiEROFS
	}
	if errors.Is(err, syscall.EXDEV) {
		return wasiEXdev
	}
	if errors.Is(err, syscall.EINVAL) {
		return wasiEInval
	}
	return wasiEIo
}

